### ISSUE TITLE
Add partial subject underline option for MarkdownBlock

### ISSUE THREAD

**Issue by justin-b-yee** [EnCiv/enciv-home#41]
## Specs

An H2 element in a Markdown block automatically has an underline that spans the full width of the parent. For some components in the homepage, we need this line to extend only partially.

![Image](https://github.com/user-attachments/assets/6764ad19-6043-4e5d-84a3-5a2aa49cf37c)

```
Old Props
----------------
<MarkdownBlock
    className = '', 
    mode = 'light', 
    children = '',
/>

New Props
----------------
<MarkdownBlock
    className = '', 
    mode = 'light', 
    lineWidth = 'full'
    children = '',
/>

```

## Tasks

- [ ] Add a 'lineWidth' prop that takes either 'full' or 'partial'.
- [ ] The default value of lineWidth should be 'full'.
- [ ] The partial width should be derived from the screen width (i.e. consistent regardless of parent width)
- [ ] Add a story in markdown-block.stories.js to test the lineWidth prop set to 'partial'.

## [Figma](https://www.figma.com/design/enAOpp07bF6ZhuXXw13Ttx/EnCiv?node-id=2-348&t=zVZOA096dY3MyUKz-4)

![Image](https://github.com/user-attachments/assets/beed1346-70d6-4b59-a7c0-4b4f0a5c5d97)

**Comment by ddfridley** [comment]
Here is a hint for how to do a fixed with border on the bottom: https://www.steckinsights.com/shorten-length-border-bottom-pure-css/#:~:text=There%20isn't%20a%20way,Done.

**Comment by RobH0** [comment]
Hello @ddfridley and @justin-b-yee ,

I would like to contribute to EnCiv by working on this as my first issue. Please may I be assigned to this issue?

**Comment by ddfridley** [comment]
@RobH0 Thank you for volunteering. It has been assigned.  Please also join our [slack](https://docs.google.com/forms/d/e/1FAIpQLSee58BUiy12dtloG9pLITsELcNldIwXcEtCotV9r95BZJSIVA/viewform?usp=sf_link) channel by filling out the form and getting the link to join.

**Comment by RobH0** [comment]
I've made the following pull request to address this issue: #46

**Comment by RobH0** [comment]
> @RobH0 Thank you for volunteering. It has been assigned. Please also join our [slack](https://docs.google.com/forms/d/e/1FAIpQLSee58BUiy12dtloG9pLITsELcNldIwXcEtCotV9r95BZJSIVA/viewform?usp=sf_link) channel by filling out the form and getting the link to join.

Thank you @ddfridley. I will fill out the form.
