### ISSUE TITLE
MarkdownBlock with header icon

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/enciv-home#43]
## Specs

There should be an prop for MarkdownBlock to take an icon, similar to TextBlock. The icon appears above the subject.

## Tasks
- [x] Add the "iconName" prop to the MarkdownBlock component.
- [x] If iconName is not provided, MarkdownBlock works as it does now.
- [x] If it is provided, lookup the icon in the svgr directory to display it (see Textblock icon#34 for example)
- [x] Copy the [three icons](https://www.figma.com/design/enAOpp07bF6ZhuXXw13Ttx/EnCiv?node-id=31-269&t=TaN0TVOfawCxCVLX-4) from Figma as SVGs, and create a file for each in app/assets/svg. 
- [x] Add a story in markdown-block.stories.js to test the iconName prop.

## [Figma](https://www.figma.com/design/enAOpp07bF6ZhuXXw13Ttx/EnCiv?node-id=2-262&t=UkDMmQWE3QSEfoPp-4)
![Image](https://github.com/user-attachments/assets/336ff89b-c8d1-4c5e-9370-d127cd6d6b76)
