### ISSUE TITLE
TextBlock with side image

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/enciv-home#44]
## Specs

Add prop for a TextBlock to take a side image. There's already an existing side prop to specify right or left.

```
<TextBlock
     ...oldProps,
     imgUrl = '',
/ >

```

## Tasks
- [x] Add the 'imgUrl' prop to the TextBlock component.
- [x] If imgUrl is not provided, TextBlock works as it does now.
- [x] Image should be displayed at approx. half the screen width (check Figma) on "side".
- [x] In condensed/mobile mode, display the image below the text content.
- [x] Add stories in text-block.stories.js to test the new prop.
- [x] Add a block to home.stories.js to display this and match the mockup.
- [x] User this URL https://res.cloudinary.com/hf6mryjpf/image/upload/v1721882509/assets%20enciv-home%202024/0a73bf0c-dcd6-4ec9-a0e8-68034c4494cb.png

## [Figma](https://www.figma.com/design/enAOpp07bF6ZhuXXw13Ttx/EnCiv?node-id=31-262&t=b19Mwvcpnw3w8iMP-4)

![Image](https://github.com/user-attachments/assets/40f590f7-efde-4d93-9fe7-22fa2ececa67)
