### ISSUE TITLE
MarkdownBlock with image

### ISSUE THREAD

**Issue by justin-b-yee** [EnCiv/enciv-home#45]
## Specs

MarkdownBlock should take props to display an image either on the left, right, or top of the component.

```
<MarkdownBlock 
     ... // existing props,
     imgUrl = '',
     imgSide = 'left',
/ >

Because of the  the left and right padding when wider than maxPanelWidth, we should separate this into 2 component.  The block component above will render the MarkdownWithImage component, and apply maxPanelWidth.

The MarkdownWithImage will render the markdown and image, within the full width of the div that it is in. 

<MarkdownWithImage
     ... // existing props,
     imgUrl = '',
     imgSide = 'left',
/>

```

#48 will use MarkdownWithImage to render multiple instances of it in a block. 

### Requirements
- [x] https://github.com/EnCiv/enciv-home/issues/41

## Tasks

- [x] Add props 'imgUrl' and 'imgSide'. See defaults above.
- [x] If imgUrl is not provided, MarkdownBlock works as it does now.
- [x] If side is 'top', image should be displayed above the subject (or in place of it if there is no subject)
- [x] If 'left' or 'right', side image should be displayed at approx. half the screen width (check Figma).
- [x] In condensed/mobile mode, display the side image below the text content.

### Stories
- [x] Add stories in markdown-block.stories.js to test these new props.
- [x] Add a block to home.stories.js to display a Markdown block w/ side image like in the mockup.

### Top Image w/ no subject

![Image](https://github.com/user-attachments/assets/cbeec7bf-7dd2-4f53-a0dc-c328c1baf495)

### Side Image

![Image](https://github.com/user-attachments/assets/a93057e1-d16c-4e6c-b243-e50f63893f8b)

**Comment by aneelabanda** [comment]
Can you assign this to me

**Comment by ddfridley** [comment]
@aneelabanda  please look through your email from github or maybe your span for an invitation to join the EnCiv developers team. I can not find a way to resend it from github.
