### ISSUE TITLE
MarkdownBlockGroup component

### ISSUE THREAD

**Issue by justin-b-yee** [EnCiv/enciv-home#48]
## Specs

Create a new component that displays multiple MarkdownBlocks.

```
<MarkdownBlockGroup
     title = '',
     children = [],
     maxCols = 4,
>
```

### Requirements

Note: These are only really needed to display in home.stories.js - the component can still be worked on without these. 
- [ ] https://github.com/EnCiv/enciv-home/issues/45
- [ ] https://github.com/EnCiv/enciv-home/issues/43

## Tasks
- [ ] Create a new file: components/markdown-block-group.jsx
- [ ] If no title is provided, don't leave any spacing above the MarkdownBlocks.
- [ ] The children are spaced and sized evenly up to maxCols components per row at fullscreen. 
- [ ] As the window shrinks, the grid layout should adapt responsively to ensure columns are a reasonable size.
- [ ] In condensed/mobile mode, use a single column to display all children.
- [ ] Create a new stories file "markdown-block-group.stories.js" to test different configurations of these props.
- [ ] Add two blocks to home.stories.js to display MarkdownBlockGroups like those in the mockup.

### Example 1
![Image](https://github.com/user-attachments/assets/f69254b6-c337-48d7-9a7f-eea19ac56760)

### Example 2
![Image](https://github.com/user-attachments/assets/ed32ffaa-24de-4c28-ae70-3a704d2d45a0)

**Comment by ddfridley** [comment]
This looks good, but here are a few things to consider. And I think it's more educational if I write the changes and reasons here - rather than just making the changes. 

In terms of the UI design, the number across needs to be either maxCols (or targetCols or just cols ) or 1 wide when width less than condensedWidthBreakPoint.  It disrupts the ui for it to be 3 and 1,  or 2 and 1.  

Also, like other block components, there is theme.maxPanelWidth that is the maxmum width. See text-block for example. 

Instead of children, use blocks as the prop, and like app/web-componnents/home.js this component can take named blocks from props and look up the corresponding react component.  -- this is so the data for what's in the MarkDownBlockGroup can come from the database.  Perhaps Blocks needs to be exported or become a separate component. 

In enciv-home, and in the future in civil-pursuit - we want to reserve .jsx for old react class components. for functional react components we want to use .js -- they all compiles either way.    It's helps differentiate, and it's just a style that was settled on by team members in the undebate project. 

I think this needs to support mode for subject color and background color.

**Comment by justin-b-yee** [comment]
> This looks good, but here are a few things to consider. And I think it's more educational if I write the changes and reasons here - rather than just making the changes.
> 
> In terms of the UI design, the number across needs to be either maxCols (or targetCols or just cols ) or 1 wide when width less than condensedWidthBreakPoint. It disrupts the ui for it to be 3 and 1, or 2 and 1.
> 
> Also, like other block components, there is theme.maxPanelWidth that is the maxmum width. See text-block for example.
> 
> Instead of children, use blocks as the prop, and like app/web-componnents/home.js this component can take named blocks from props and look up the corresponding react component. -- this is so the data for what's in the MarkDownBlockGroup can come from the database. Perhaps Blocks needs to be exported or become a separate component.
> 
> In enciv-home, and in the future in civil-pursuit - we want to reserve .jsx for old react class components. for functional react components we want to use .js -- they all compiles either way. It's helps differentiate, and it's just a style that was settled on by team members in the undebate project.
> 
> I think this needs to support mode for subject color and background color.

Thanks for the input! This clarifies things a bit - I updated the specs to take these into consideration.

**Comment by RobH0** [comment]
Waiting for issues #43 and #45 to be completed and merged before finishing the addition of MarkdownBlockGroup examples to `home.stories.js`.

**Comment by ddfridley** [comment]
@RobH0 What is the status of this? If you are not going to be able to work on it, can you unassign yourself or let me know? Thanks.

**Comment by RobH0** [comment]
> @RobH0 What is the status of this? If you are not going to be able to work on it, can you unassign yourself or let me know? Thanks.

Hi @ddfridley, sorry for the late reply. Just want to confirm that I am still working this issue. I've been waiting for issue #45 to be completed so I can finish the story to mockup the example 1 screenshot within this issue.
