### ISSUE TITLE
Action button with icon

### ISSUE THREAD

**Issue by justin-b-yee** [EnCiv/enciv-home#55]
## Specs

Add props to make the ActionButton take an icon.
```
<ActionButton
     ... // existing props
    iconName = '',
    side = 'right'
>
```

## Tasks
- [x] Add the iconName and side props. 
- [x] If iconName is not provided, the button displays as it does now with only text.
- [x] If iconName is provided, lookup the icon in the svgr directory and display it on the specified side. (example:
https://github.com/EnCiv/enciv-home/blob/2b9e6be7a053a933890344f8eb744f1f4ded627a/app/components/text-block.js#L10-L14
- [x] Copy the icon from Figma as an SVG, and create a file for it in app/assets/svg.
- [x] Add a story in stories/action-button.stories.js to showcase the button with icon.

## [Figma](https://www.figma.com/design/enAOpp07bF6ZhuXXw13Ttx/EnCiv?node-id=299-16&t=9XzDCsFvT8ezDB9n-4)

![Image](https://github.com/user-attachments/assets/5fc7bbb7-d35d-4a19-bc8c-43414ffb4c06)
