### ISSUE TITLE
Action button transparent mode

### ISSUE THREAD

**Issue by justin-b-yee** [EnCiv/enciv-home#56]
## Specs

Add a new prop to style the action button according to the mockup. 

```
<ActionButton
     ..., // existing props
    mode = 'default'
>
```

## Tasks
- [x] If the mode prop is 'default', the button's style is as it is now. 
- [x] If mode is 'transparent', the button text and outline should be white, and the background color transparent.
- [x] Add a story to action-button.stories.js to showcase the transparent mode button.

## [Figma](https://www.figma.com/design/enAOpp07bF6ZhuXXw13Ttx/EnCiv?node-id=299-15&t=ZKzW48VAIAq8KwRM-4)

![Image](https://github.com/user-attachments/assets/c8d34433-badc-4ee0-9fdc-6bc8f46ad505)
