### ISSUE TITLE
Allow content alignment options for HeroBlock

### ISSUE THREAD

**Issue by justin-b-yee** [EnCiv/enciv-home#58]
## Specs

Currently, HeroBlock hardcodes the textAlign style into the subject and button. We want flexibility to display left aligned (or right) content too.

```
<HeroBlock
   ... // existing props
   alignContent: 'center'
/>
```

## Tasks
- [x] Add the alignContent prop to HeroBlock. 
- [x] Set the alignment of the subject and action button to alignContent's value. 
- [x] Ensure content has adequate space between it and the edge of the screen. When the viewport is wider, the text area should remain within theme.maxPanelWidth and centered. 
- [x] Add a story to hero-block.stories.js to showcase a HeroBlock with left aligned children. 

## [Figma](https://www.figma.com/design/enAOpp07bF6ZhuXXw13Ttx/EnCiv?node-id=31-215&t=aM9CE6z0IBFUvHom-4)
![Image](https://github.com/user-attachments/assets/8114a580-bb17-4e91-9d02-4d3bcfe72a41)

**Comment by ddfridley** [comment]
@justin-b-yee  I added "When the viewport is wider, the text area should remain within theme.maxPanelWidth and centered. "
